# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCheckoutcompleted():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_checkoutcompleted(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.find_element(By.ID, "user-name").click()
    self.driver.find_element(By.ID, "user-name").send_keys("standard_user")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("secret_sauce")
    self.driver.find_element(By.ID, "login-button").click()
    self.driver.find_element(By.ID, "add-to-cart-sauce-labs-backpack").click()
    self.driver.find_element(By.CSS_SELECTOR, ".shopping_cart_link").click()
    self.driver.find_element(By.ID, "checkout").click()
    self.driver.find_element(By.ID, "first-name").click()
    self.driver.find_element(By.ID, "first-name").send_keys("Tuba")
    self.driver.find_element(By.ID, "last-name").click()
    self.driver.find_element(By.ID, "last-name").send_keys("Bezek")
    self.driver.find_element(By.ID, "postal-code").click()
    self.driver.find_element(By.ID, "postal-code").send_keys("72070")
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.ID, "continue").click()
    self.driver.find_element(By.ID, "finish").click()
    self.driver.find_element(By.ID, "checkout_complete_container").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"complete-text\"]").text == "Your order has been dispatched, and will arrive just as fast as the pony can get there!"
  
